// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHfsGU0-XC1rWd2PiBe245eOeethkP2tQ', // <-- NOVO VALOR
    appId: '1:787952710825:android:d65eb905a7dcfac58b25b8', // <-- NOVO VALOR
    messagingSenderId: '787952710825', // <-- NOVO VALOR (project_number)
    projectId: 'untold-app-prod', // <-- NOVO VALOR
    storageBucket: 'untold-app-prod.appspot.com', // <-- NOVO VALOR
  );

  // --- VALORES PARA IOS (vindos do GoogleService-Info.plist) ---
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnRTXKUwPXCDSNbIEmu_9Uwkbb3SVuOcM', // <-- NOVO VALOR
    appId:
        '1:787952710825:ios:9b8e987e6e4cabeb8b25b8', // <-- NOVO VALOR (GOOGLE_APP_ID)
    messagingSenderId: '787952710825', // <-- NOVO VALOR (GCM_SENDER_ID)
    projectId: 'untold-app-prod', // <-- NOVO VALOR
    storageBucket: 'untold-app-prod.appspot.com', // <-- NOVO VALOR
    iosBundleId: 'com.app.untold', // <-- Mantém o mesmo (BUNDLE_ID)
  );
}
